### ISSUE TITLE
Endless spin blank screen on first use

### ISSUE THREAD

**Issue by ibaranov-cp** [kiibohd/configurator#127]
Downloaded 1.0.0, installed drivers. I can flash my Infinity Ergodox, however when I try to select it (or any other keyboard) to configure, I just get the blue spinning wheel. I am on Windows 7.
What are next steps? I have tried running as administrator.

**Comment by smasher816** [comment]
This is most likely a network problem when retrieving the layout (there's no error popup on failure right now but it will be in the next release).

You can confirm by going to View -> Toggle Developer Tools -> Network.

**Comment by ibaranov-cp** [comment]
+1 That's it. Will try under a different network.

**Comment by ibaranov-cp** [comment]
Works under different network, please feel free to close (but it is good this issue now exists for others to see :)
