### ISSUE TITLE
Ergodox Infinity: Compiled firmware doesn't work properly

### ISSUE THREAD

**Issue by thegreatco** [kiibohd/configurator#137]
When I attempt to compile firmware for the infinity (both on the webiste and using the Kiibohd Configurator app) the resulting firmware ends up in a very weird state. Its like the keyboard is stuck in some combination of layer 1 and the base layer. For example, my base layer is a fairly standard keyboard layout, with the lower vertical button on the left set to bring up layer 1 (not a lock, just a shift) with the key in the upper left of that side being set to "Flash" in layer 1. Without pressing any other keys (no layer shift) pressing the upper left button puts the keyboard into flash mode. Additionally, most of the other keys appear to be shifted to the right by one column.

I have tried both "latest" and "lts" when downloading the firmware. I have also tried flashing the newest firmware from [here](https://github.com/kiibohd/controller/releases). To no avail. I've been hesitant to try reflashing the bootloader so I don't know if that fixes it or not.

*EDIT* I tried flashing the bootloader to no effect.
*EDIT* I was able to get it to flash and work _mostly_ right. The issue seems to be with the display now, it doesn't show the layer number any more, nor does it change color like it used to.

**Comment by djak250** [comment]
Same except flashing the default bootloader and keymaps from the link you posted got me up and running. Any custom keymaps though and it's back to SOL.

**Comment by haata** [comment]
The LCD screens have been fixed with the most recent firmware update.
