### ISSUE TITLE
LCD Screens Not Displaying Page and Layers Not Toggling

### ISSUE THREAD

**Issue by cptbldbrd** [kiibohd/configurator#159]
Just flashed my keyboards and the LCD screens are no longer displaying which layer I am on. Also, if the layer is changed, it will not go back to any other layer.

**Comment by Farreep** [comment]
Can confirm, I am having both of these issues.  LCD remains on white layer 1 logo, and layer changes are sticky/broken.  I can change into numpad layer, but not out of it.

**Comment by tracer99** [comment]
I'm assuming this is for the Infinity ergodox. 

I was lucky in that I saved an old firmware from my layout and was able to re-flash it. But the new one is unusable.

**Comment by cptbldbrd** [comment]
Yeah it was about the Infinity Ergodox. I bought a pair on r/mechmarket but after flashing it I ran into this issue. I have since gotten rid of them and built my own pair. It doesn't seem to like this issue is getting attention.

**Comment by haata** [comment]
Please try the beta firmware release here https://github.com/kiibohd/controller/releases/tag/v0.5.7-beta1

https://github.com/kiibohd/controller/releases/download/untagged-482525da9bccdb2d4bad/ergodox.left.v0.5.7-beta1.dfu.bin
https://github.com/kiibohd/controller/releases/download/untagged-482525da9bccdb2d4bad/ergodox.right.v0.5.7-beta1.dfu.bin

If this helps, I can make it an official release and push it to the configurator.

**Comment by tracer99** [comment]
@haata This firmware works great! Looks like all features are working properly including all layers switches and toggles.

**Comment by Omnicraft** [comment]
@haata This definitely fixes the LCD issues on Ergodox infinity and needs to get updated so that the configurator can be usefull again. Manual compilation is nontrivial and most people dont' bother.

**Comment by haata** [comment]
I'll be pushing it in the next couple of days (working through an annoying bug before I can push it to the configurator).

**Comment by tracer99** [comment]
Any ETA on this new release?

**Comment by Omnicraft** [comment]
It's working for me on the latest configurator, I'm using an ergodox
infinity

**Comment by tracer99** [comment]
N00b question. Is the configurator version independent from the firmware release? (as in does the configurator download it dynamically?)

**Comment by haata** [comment]
Yes, the configurator version is independent. The firmware is built on a remote server and the configurator just downloads the binary to flash onto your keyboard.
