### ISSUE TITLE
Hexgears Gemini missing from list?

### ISSUE THREAD

**Issue by jwmann** [kiibohd/configurator#170]
I'm not sure how nobody has mentioned this yet or maybe I missed something in the readme but I don't see the Hexgears Gemini keyboards in the list.

Am I supposed to use the K-Type keyboard for my Gemini instead?

**Comment by haata** [comment]
A different version of the configurator is used for Gemini.
Firmware wise, they use the same backend for updates.

https://github.com/hexgears/configurator
