### ISSUE TITLE
NightFox Won't Flash Through Configurator

### ISSUE THREAD

**Issue by Xixeonn** [kiibohd/configurator#173]
I just put together one the other day from someone who had bought this from the original release. When I was going to remap the keys I'm having troubles with the number keys (they are all f keys for some reason) and the backspace is delete and won't change through flashing. I followed the instructions from https://input.club/configurator-setup/ 
As well as the other site that was listed initially https://input.club/configurator-setup/
When trying to used Zadig I can’t find the recommended API Interface (Interface 5) To continue attempting through that method.
![reeee](https://user-images.githubusercontent.com/54999375/81131355-831a2980-8f10-11ea-81f6-d6d9d86fbc5b.png)
F1-12 is 1 through +
Esc is only flashing the device.
Backspace is delete
Page up and down are the volume up and downs.
Arrow keys are your page up and down plus delete and end.
I have flashed the device with Truefox profile many times.

**Comment by haata** [comment]
Those instructions are quite out of date (thanks for reporting, totally forgot about that page!).

Please use this wiki now: https://kiibohd.github.io/wiki/#/Quickstart
Zadig is now integrated into the configurator so you don't need to worry about installing it.

**Comment by Xixeonn** [comment]
I have tried that one as well sorry. It was meant to be that link and the other instead of a double post. No amount of flashing I've done has changed this so far.
