### ISSUE TITLE
Some keys do not properly map Configurator v0.3.0

### ISSUE THREAD

**Issue by felixekn** [kiibohd/configurator#40]
When remapping keys with the client side Kiibohd Configurator (v0.0.3), some keys (I've experienced vol- and vol+ remapped to Print and SCLK) won't remap. The UI shows the correct mapping and the outputed JSON is correct but the kiibohd.dfu.bin when loaded onto the keyboard isn't.

**Comment by jbondeson** [comment]
@felixekn I'm going to need a little more information. Which keys and keyboard are you have an issue with?

**Comment by felixekn** [comment]
@jbondeson I just went and reflashed my board with the problematic firmware downloaded from the client configurator. This time around the vol- and vol+ were correctly mapped to Print and SCLK after flashing. Not sure what went wrong the first time since I flashed from the exact same firmware download. Wish I could replicate the problem but it doesn't look like I can. 

I am flashing through terminal using dfu-util -D since the configurator's flash feature is a bit confusing to me.

**Comment by dmgm** [comment]
@jbondeson if you dont hit download firmware and just go straight to flash, well it wont. It just sits there until you unplug your keyboard. I guess I did this and had downloaded no previous firmware.

I'm sorted now, but thought I'd provide the feedback. It did cause confusion.

**Comment by jbondeson** [comment]
Closing due to UI changes in d2449c072a28f6d75cc56f58cb844c889802006c that remove the confusion.
