### ISSUE TITLE
Custom KLL changes under specific circumstance

### ISSUE THREAD

**Issue by johnny12times** [kiibohd/configurator#56]
If you have Custom KLL on a layer (not the base), then select the custom kll, and without modifying it then switch layers, it will replace the custom kll on that layer with whatever the base layer is set to. This is on the 0.3.1 version of the configurator for windows.

**Comment by johnny12times** [comment]
Additional details:

Keyboard: K-Type
Behavior reproducible reliably when restoring a layout.

**Comment by jbondeson** [comment]
Fixed in 387f3a27e30d3f3e6ed196f6de7c439586a646cd
