### ISSUE TITLE
"?" macro error

### ISSUE THREAD

**Issue by hallucinatesgirls** [kiibohd/configurator#63]
The configurator is assigning "e?" instead of "?". Cheers

**Comment by jbondeson** [comment]
Can you be a little more specific as to what is happening?

Also OS and the language setting will be helpful no doubt.

**Comment by hallucinatesgirls** [comment]
There's a typo in the code where an e has accidentally been added. You can see this in the JSON raw layout:
![capture1](https://user-images.githubusercontent.com/17761747/33354383-949ebd5c-d517-11e7-94e2-24c2baf72578.PNG)
OS: Windows, Language: English

**Comment by hallucinatesgirls** [comment]
This appears to be the culprit in the predefined.cljs file
![capture1](https://user-images.githubusercontent.com/17761747/33399691-68daedd4-d5b8-11e7-919e-84ca9b147b1f.PNG)

**Comment by jbondeson** [comment]
What a fun typo. I'll get that into the next build later that I'll be pushing later this week.
