### ISSUE TITLE
Fingerprint visualization doesn't work when keys are pressed very quick.

### ISSUE THREAD

**Issue by spirosag** [kiibohd/configurator#64]
When a 2nd key is pressed after the first one, the 2nd key doesn't light up when using the default fingerprint visualization

**Comment by johanntang** [comment]
Dupe of https://github.com/kiibohd/configurator/issues/64

**Comment by spirosag** [comment]
@johanntang #64 is this one :) I guess it's a dupe of some other ticket

**Comment by jbondeson** [comment]
It's a dupe of #45
