### ISSUE TITLE
Cannot use configurator as a normal user on linux

### ISSUE THREAD

**Issue by AevumDecessus** [kiibohd/configurator#76]
Item | Version
--- | ---
OS | Ubuntu 16.04 LTS
Configurator | 0.4.1 x64
dfu-util | 0.8

Running the configurator as a normal user with a K-Type plugged in shows the following:
![image](https://user-images.githubusercontent.com/1137023/34421064-145abdd2-ebdb-11e7-9f6f-ea22f3c9e50b.png)

Attempting to flash the keyboard produces the following error:
![image](https://user-images.githubusercontent.com/1137023/34421085-2fed8ff2-ebdb-11e7-98ed-5bd4765e55d4.png)

Running the configurator as sudo allows full functionality.

Adding udev rules per #75 resolves this completely and allows full functionality without use of sudo

**Comment by jbondeson** [comment]
Merged.
