### ISSUE TITLE
Deprecate U"Function", layerShift, layerLatch and layerLock usage

### ISSUE THREAD

**Issue by haata** [kiibohd/configurator#94]
Going forward we should be using the new layer syntax as it's more general and works for both triggers and results. The old syntax was using only capabilities and hacky aliases.

This also means we should be deprecating stdFuncMap (and lcdFuncMap once it can be replaced; should be possible with replace:state and Layer Triggers).

```
Layer[1] : <result>; # Layer 1 shift
LayerShift[2] : <result>; # Layer 2 shift
LayerLatch[3] : <result>; # Layer 3 latch
LayerLock[4] : <result>; # Layer 4 lock
```

layerShift, layerLatch and layerLock won't change, so the previous method will continue to work.

**Comment by jbondeson** [comment]
Released in v1.0
